### PR TITLE
configure circle ci

### PR DESCRIPTION
**Pull request by xh3b4sd**
We want to try out to use this for automatic branch cleanup via Github Actions. Just setting up circle to get the Docker image build in our usual way.

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
Great to have automation here. <3

LGTM but CI is unhappy about something.

**Review by MarcelMue — APPROVED** [review]
LGTM

**Comment by xh3b4sd** [comment]
Well, the build fails with the license file of the forked repo. That does not work at all with our tooling. How to deal with that?

**Comment by MarcelMue** [comment]
I am not big into licenses but can we change it? Otherwise we'll have to adapt architect :(

**Comment by xh3b4sd** [comment]
That is the error. 

```
repo 'LICENSE' file does not contain required text 'Copyright 2016 - 2019 Giant Swarm GmbH'
```

The license file says this. 

```
Copyright (c) 2019 Jessie Frazelle
```

Should we adapt `architect` to only check for the `Copyright.*2019` pattern?

**Comment by rossf7** [comment]
OMG licenses again :( For now loosening the pattern makes sense to me.

**Pull request merged**
